let me,items=[],cats=[],cart=[],orders=[],roles=[],users=[],perms=[];
const $=x=>document.getElementById(x),money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n),toast=t=>{let x=$("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",2200)};
const navs=[["dashboard","⌂ Dashboard"],["items","▣ Barang"],["cart","🛒 Keranjang"],["orders","▤ Pesanan"],["history","◷ Riwayat"],["stock","↕ Stok"],["roles","♜ Role & Permission"],["users","♙ User"]];
async function api(url,opt={}){let r=await fetch(url,{...opt,headers:opt.body instanceof FormData?opt.headers:{"Content-Type":"application/json",...(opt.headers||{})}});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Terjadi kesalahan");return d}
async function init(){try{me=await api("/api/me");start()}catch{showLogin()}$("loginForm").onsubmit=login;$("logout").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()}}
async function login(e){e.preventDefault();try{await api("/api/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});location.reload()}catch(e){toast(e.message)}}
function showLogin(){$("login").classList.remove("hidden");$("app").classList.add("hidden")}
function start(){$("login").classList.add("hidden");$("app").classList.remove("hidden");$("meName").textContent=me.name;$("meRole").textContent=me.role;perms=me.permissions;buildNav();loadAll();show("dashboard")}
function allow(p){return perms.includes(p)}
function buildNav(){$("nav").innerHTML=navs.filter(n=>n[0]=="dashboard"||allow(n[0])).map(n=>`<button data-p="${n[0]}">${n[1]}</button>`).join("");document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.p))}
async function loadAll(){[items,cats,cart,orders]=await Promise.all([api("/api/items"),api("/api/categories"),api("/api/cart"),api("/api/orders")]);if(allow("roles"))roles=await api("/api/roles");if(allow("users"))users=await api("/api/users");render(document.querySelector(".page:not(.hidden)")?.id||"dashboard")}
function show(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(p).classList.remove("hidden");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.p==p));$("title").textContent=navs.find(x=>x[0]==p)?.[1].replace(/^.\s/,"")||"Dashboard";render(p)}
function render(p){({dashboard:dash,items:itemsPage,cart:cartPage,orders:ordersPage,history:historyPage,stock:stockPage,roles:rolesPage,users:usersPage}[p]||dash)()}
async function refresh(){await loadAll();render(document.querySelector(".page:not(.hidden)").id)}
async function dash(){let d=await api("/api/dashboard");$("dashboard").innerHTML=`<div class="stats"><div class="card"><small>Total Barang</small><strong>${d.items}</strong></div><div class="card"><small>Total Stok</small><strong>${d.stock}</strong></div><div class="card"><small>Pending</small><strong>${d.pending}</strong></div><div class="card"><small>Disetujui</small><strong>${d.approved}</strong></div></div><div class="panel" style="margin-top:14px"><h3>Pesanan Pending</h3>${orders.filter(x=>x.status=="Pending").slice(0,10).map(o=>`<div class="row"><span><b>${o.order_no}</b><br><small>${o.requester} • ${money(o.total)}</small></span>${allow("approve")?`<span><button class="btn" onclick="approve(${o.id},1)">ACC</button> <button class="btn" onclick="approve(${o.id},0)">Tolak</button></span>`:"Pending"}</div>`).join("")||"<div class=row>Tidak ada pesanan pending.</div>"}</div>`}
function itemsPage(){let q=($("iq")?.value||"").toLowerCase();$("items").innerHTML=`<div class=section><div><h2>Barang</h2><small>Inventory online + foto barang.</small></div>${allow("items_manage")?`<button class=primary onclick="itemModal()">+ Tambah Barang</button>`:""}</div><div class=toolbar><input id=iq placeholder="Cari barang..." value="${q}" oninput="itemsPage()"><select onchange="itemsPage()"><option>Semua kategori</option>${cats.map(c=>`<option>${c.name}</option>`)}</select></div><div class=grid>${items.filter(i=>(i.name+" "+i.code).toLowerCase().includes(q)).map(i=>`<div class="card item"><img src="${i.image||"logo.png"}"><small>${i.code} • ${i.category||"-"}</small><h3>${i.name}</h3><div class=price>${money(i.price)}</div><p>Stok: <b>${i.stock}</b></p><div class=actions>${allow("order")&&i.stock>0?`<button class=primary onclick="addCart(${i.id})">+ Keranjang</button>`:""}${allow("items_manage")?`<button class=btn onclick="itemModal(${i.id})">Edit</button><button class=btn onclick="delItem(${i.id})">Hapus</button>`:""}</div></div>`).join("")}</div>`}
async function addCart(id){try{await api("/api/cart",{method:"POST",body:JSON.stringify({item_id:id,qty:1})});await refresh();toast("Barang masuk keranjang")}catch(e){toast(e.message)}}
function cartPage(){let total=cart.reduce((s,x)=>s+x.qty*x.price,0);$("cart").innerHTML=`<div class=section><div><h2>Keranjang</h2><small>Pesanan akan menunggu ACC.</small></div></div><div class=panel>${cart.map(x=>`<div class=cartrow><img src="${x.image||"logo.png"}"><div><b>${x.name}</b><br><small>${money(x.price)}</small></div><div class=qty><button class=btn onclick="cartQty(${x.id},${x.qty-1})">−</button><b>${x.qty}</b><button class=btn onclick="cartQty(${x.id},${x.qty+1})">+</button></div></div>`).join("")||"Keranjang kosong."}${cart.length?`<div class=total><b>${money(total)}</b><button class=primary onclick="sendOrder()">Kirim Pesanan</button></div>`:""}</div>`}
async function cartQty(id,qty){await api("/api/cart/"+id,{method:"PUT",body:JSON.stringify({qty})});await refresh()}
async function sendOrder(){try{let d=await api("/api/orders",{method:"POST"});await refresh();toast("Pesanan "+d.order_no+" menunggu ACC")}catch(e){toast(e.message)}}
function ordersPage(){let list=orders;$("orders").innerHTML=`<div class=section><h2>Pesanan</h2></div><div class=panel><table><thead><tr><th>ID</th><th>Pemesan</th><th>Detail</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${list.map(o=>`<tr><td>${o.order_no}</td><td>${o.requester}</td><td>${o.details||"-"}</td><td>${money(o.total)}</td><td><span class="badge ${o.status}">${o.status}</span></td><td>${o.status=="Pending"&&allow("approve")?`<button class=btn onclick="approve(${o.id},1)">ACC</button> <button class=btn onclick="approve(${o.id},0)">Tolak</button>`:"-"}</td></tr>`).join("")}</tbody></table></div>`}
async function approve(id,yes){try{await api("/api/orders/"+id+"/"+(yes?"approve":"reject"),{method:"POST"});await refresh();toast(yes?"Pesanan di-ACC":"Pesanan ditolak")}catch(e){toast(e.message)}}
function historyPage(){let list=orders.filter(o=>o.status!="Pending");$("history").innerHTML=`<div class=section><h2>Riwayat</h2></div><div class=panel><table><thead><tr><th>ID</th><th>Pemesan</th><th>Total</th><th>Status</th><th>Proses</th></tr></thead><tbody>${list.map(o=>`<tr><td>${o.order_no}</td><td>${o.requester}</td><td>${money(o.total)}</td><td>${o.status}</td><td>${o.approver||"-"}</td></tr>`).join("")}</tbody></table></div>`}
async function stockPage(){let m=await api("/api/movements");$("stock").innerHTML=`<div class=section><h2>Stok</h2><button class=primary onclick="stockModal()">+ Stok Masuk</button></div><div class=panel><table><thead><tr><th>Tanggal</th><th>Barang</th><th>Jenis</th><th>Qty</th><th>Petugas</th></tr></thead><tbody>${m.map(x=>`<tr><td>${x.created_at}</td><td>${x.item}</td><td>${x.type}</td><td>${x.qty}</td><td>${x.user||"-"}</td></tr>`).join("")}</tbody></table></div>`}
function rolesPage(){$("roles").innerHTML=`<div class=section><div><h2>Role & Permission</h2><small>Buat role tanpa menyentuh kode.</small></div><button class=primary onclick="roleModal()">+ Buat Role</button></div><div class=grid>${roles.map(r=>`<div class=role"><h3>${r.name}</h3><p>${r.description||""}</p>${JSON.parse(r.permissions).map(p=>`<span class=perm>${p}</span>`).join("")}</div>`).join("")}</div>`}
function usersPage(){$("users").innerHTML=`<div class=section><div><h2>User</h2><small>Buat akun dan pilih role langsung dari website.</small></div><button class=primary onclick="userModal()">+ Tambah User</button></div><div class=panel><table><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${users.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.role}</td><td>${u.active?"Aktif":"Nonaktif"}</td><td><button class=btn onclick="editUser(${u.id})">Edit</button></td></tr>`).join("")}</tbody></table></div>`}
function openM(t,b){$("mt").textContent=t;$("mb").innerHTML=b;$("modal").classList.remove("hidden")}function closeM(){$("modal").classList.add("hidden")}
async function itemModal(id){let i=id?items.find(x=>x.id==id):null;openM(i?"Edit Barang":"Tambah Barang",`<form id=f><input id=code placeholder=Kode value="${i?.code||""}" required><input id=name placeholder="Nama barang" value="${i?.name||""}" required><select id=cat>${cats.map(c=>`<option value="${c.id}" ${i?.category_id==c.id?"selected":""}>${c.name}</option>`)}</select><input id=price type=number placeholder=Harga value="${i?.price||0}"><input id=stock type=number placeholder=Stok value="${i?.stock||0}"><input id=photo type=file accept=image/*><img id=prev class=preview src="${i?.image||"logo.png"}"><textarea id=desc placeholder=Deskripsi>${i?.description||""}</textarea><div class=modalactions><button type=button class=btn onclick=closeM()>Batal</button><button class=primary>Simpan</button></div></form>`);$("photo").onchange=e=>{let f=e.target.files[0];if(f){let r=new FileReader();r.onload=x=>$("prev").src=x.target.result;r.readAsDataURL(f)}};$("f").onsubmit=async e=>{e.preventDefault();let fd=new FormData();["code","name","cat","price","stock","desc"].forEach((x,i)=>fd.append(["code","name","category_id","price","stock","description"][i],$(x).value));if($("photo").files[0])fd.append("photo",$("photo").files[0]);try{await fetch("/api/items"+(id?"/"+id:""),{method:id?"PUT":"POST",body:fd}).then(async r=>{let d=await r.json();if(!r.ok)throw Error(d.error)});closeM();await refresh();toast("Barang tersimpan")}catch(e){toast(e.message)}}}
async function delItem(id){if(confirm("Hapus barang ini?")){try{await api("/api/items/"+id,{method:"DELETE"});await refresh();toast("Barang dihapus")}catch(e){toast(e.message)}}}
async function stockModal(){openM("Stok Masuk",`<form id=sf><select id=si>${items.map(i=>`<option value=${i.id}>${i.name} (${i.stock})</option>`).join("")}</select><input id=sq type=number min=1 placeholder=Jumlah required><textarea id=sn placeholder=Catatan></textarea><div class=modalactions><button type=button class=btn onclick=closeM()>Batal</button><button class=primary>Simpan</button></div></form>`);$("sf").onsubmit=async e=>{e.preventDefault();try{await api("/api/stock-in",{method:"POST",body:JSON.stringify({item_id:$("si").value,qty:$("sq").value,note:$("sn").value})});closeM();await refresh();toast("Stok masuk tersimpan")}catch(e){toast(e.message)}}}
async function roleModal(){openM("Buat Role",`<form id=rf><input id=rn placeholder="Nama role" required><input id=rd placeholder="Deskripsi">${permsList().map(p=>`<label><input type=checkbox value="${p}"> ${p}</label>`).join("")}<div class=modalactions><button type=button class=btn onclick=closeM()>Batal</button><button class=primary>Buat</button></div></form>`);$("rf").onsubmit=async e=>{e.preventDefault();let ps=[...document.querySelectorAll("#rf input[type=checkbox]:checked")].map(x=>x.value);try{await api("/api/roles",{method:"POST",body:JSON.stringify({name:$("rn").value,description:$("rd").value,permissions:ps})});closeM();await refresh();toast("Role dibuat")}catch(e){toast(e.message)}}}
function permsList(){return ["dashboard","items","items_manage","cart","order","orders","approve","history","stock","roles","users","roles_manage"]}
function userModal(){openM("Tambah User",`<form id=uf><input id=un placeholder="Nama lengkap" required><input id=ue type=email placeholder=Email required><input id=up placeholder="Password sementara" value="cassano123"><select id=ur>${roles.map(r=>`<option value=${r.id}>${r.name}</option>`).join("")}</select><div class=modalactions><button type=button class=btn onclick=closeM()>Batal</button><button class=primary>Buat User</button></div></form>`);$("uf").onsubmit=async e=>{e.preventDefault();try{let d=await api("/api/users",{method:"POST",body:JSON.stringify({name:$("un").value,email:$("ue").value,password:$("up").value,role_id:$("ur").value})});closeM();await refresh();alert("User dibuat. Password: "+d.temporary_password)}catch(e){toast(e.message)}}}
async function editUser(id){let u=users.find(x=>x.id==id);openM("Edit User",`<form id=eu><input id=en value="${u.name}"><select id=er>${roles.map(r=>`<option value=${r.id} ${r.name==u.role?"selected":""}>${r.name}</option>`).join("")}</select><label><input id=ea type=checkbox ${u.active?"checked":""}> Aktif</label><div class=modalactions><button type=button class=btn onclick=closeM()>Batal</button><button class=primary>Simpan</button></div></form>`);$("eu").onsubmit=async e=>{e.preventDefault();try{await api("/api/users/"+id,{method:"PUT",body:JSON.stringify({name:$("en").value,role_id:$("er").value,active:$("ea").checked})});closeM();await refresh();toast("User diperbarui")}catch(e){toast(e.message)}}}
init();