(()=>{
const style=document.createElement('style');style.id='cassano-polish';style.textContent=`
.page{animation:csPageIn .28s ease both}@keyframes csPageIn{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}
.card,.panel,.cuCard,.cuPanel,.dashPanel,.dashStat,.dashWelcome{transition:transform .2s ease,border-color .2s ease,box-shadow .2s ease}.card:hover,.panel:hover,.cuCard:hover,.dashStat:hover{transform:translateY(-2px);border-color:#48222c;box-shadow:0 14px 34px rgba(0,0,0,.18)}
.primary,.btn{transition:transform .15s ease,box-shadow .15s ease,background .15s ease}.primary:hover,.btn:hover{transform:translateY(-1px)}.primary:active,.btn:active{transform:translateY(0)}
.cuHero,.dashWelcome{position:relative}.cuHero:before,.dashWelcome:before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:#c51632;box-shadow:0 0 18px rgba(197,22,50,.5);border-radius:3px}
.cuIdentity{position:relative;overflow:hidden}.cuIdentity:after{content:'C';position:absolute;right:-10px;bottom:-35px;font:900 150px/1 Georgia,serif;color:rgba(255,255,255,.025);pointer-events:none}.cuBig{animation:csAvatar 4s ease-in-out infinite}@keyframes csAvatar{0%,100%{box-shadow:0 0 24px rgba(205,25,55,.16)}50%{box-shadow:0 0 34px rgba(205,25,55,.32)}}
#ranking .cuRows .cuRow{position:relative;min-height:62px}.cuRows .cuRow:nth-child(1){background:linear-gradient(90deg,rgba(197,22,50,.08),transparent);margin:0 -16px;padding-left:16px;padding-right:16px}.cuRows .cuRow:nth-child(1) .cuAvatar{box-shadow:0 0 18px rgba(197,22,50,.22)}.cuRows .cuRow:nth-child(2),.cuRows .cuRow:nth-child(3){opacity:.96}.cuRows .cuRank{font-weight:900}
#stock .cuRows{position:relative}#stock .cuRows:before{content:'';position:absolute;left:42px;top:16px;bottom:16px;width:1px;background:linear-gradient(#4a1c28,transparent)}#stock .cuMove{position:relative;padding-left:0;min-height:66px}#stock .cuMove:before{content:'';width:7px;height:7px;border-radius:50%;background:#c51632;box-shadow:0 0 10px rgba(197,22,50,.65);position:absolute;left:39px;top:28px;z-index:2}#stock .cuMove small:first-child{color:#6f7785}.cuIn{text-shadow:0 0 8px rgba(85,217,138,.12)}.cuOut{text-shadow:0 0 8px rgba(255,115,139,.12)}
.dashStat strong{transition:transform .35s ease}.dashWelcome{overflow:hidden}.dashWelcome:after{animation:csWatermark 7s ease-in-out infinite alternate}@keyframes csWatermark{from{transform:translateX(0) rotate(-4deg)}to{transform:translateX(-12px) rotate(4deg)}}
.csLoading{position:relative;overflow:hidden;background:#15171b!important;color:transparent!important;border-color:#252830!important}.csLoading:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.045),transparent);transform:translateX(-100%);animation:csShimmer 1.2s infinite}@keyframes csShimmer{to{transform:translateX(100%)}}
.item img.csImgLoading{background:linear-gradient(90deg,#0b0c0f,#17191e,#0b0c0f);background-size:200% 100%;animation:csShimmerBg 1.2s infinite}@keyframes csShimmerBg{to{background-position:-200% 0}}
#toast.csToast{display:block!important;opacity:0;transform:translateY(10px);pointer-events:none;background:linear-gradient(145deg,#17191e,#101115);border:1px solid #4a2029;color:#fff;padding:12px 15px;border-radius:10px;box-shadow:0 14px 35px rgba(0,0,0,.45),0 0 20px rgba(197,22,50,.1);transition:opacity .2s,transform .2s;max-width:330px}#toast.csToast.show{opacity:1;transform:none}#toast.csToast b{color:#ff536b;display:block;font-size:11px;letter-spacing:.4px;margin-bottom:3px}#toast.csToast span{color:#aeb4bf;font-size:10px}
.cuHead b,.dashPanelHead h3{letter-spacing:.15px}.cuHero h2{letter-spacing:-.4px}
@media(max-width:700px){#stock .cuRows:before{left:32px}#stock .cuMove:before{left:29px}.cuRows .cuRow:nth-child(1){margin:0 -13px;padding-left:13px;padding-right:13px}}
@media(prefers-reduced-motion:reduce){.page,.cuBig,.dashWelcome:after,.csLoading:after,.item img.csImgLoading{animation:none!important}}
`;document.head.appendChild(style);
const toast=document.getElementById('toast');
function notify(title,msg){if(!toast)return;toast.className='csToast show';toast.innerHTML=`<b>✓ ${title}</b><span>${msg}</span>`;clearTimeout(window.__csToast);window.__csToast=setTimeout(()=>toast.classList.remove('show'),2400)}
window.csNotify=notify;
function reveal(root=document){root.querySelectorAll('.item img').forEach(img=>{if(img.dataset.polished)return;img.dataset.polished='1';img.classList.add('csImgLoading');if(img.complete)img.classList.remove('csImgLoading');else img.addEventListener('load',()=>img.classList.remove('csImgLoading'),{once:true})});root.querySelectorAll('.page > *, .dashPanel, .dashStat, .cuCard').forEach((el,i)=>{if(el.dataset.reveal)return;el.dataset.reveal='1';el.style.animationDelay=Math.min(i*25,180)+'ms'})}
const obs=new MutationObserver(ms=>{for(const m of ms){if(m.addedNodes.length)reveal(m.target instanceof Element?m.target:document)}});obs.observe(document.body,{subtree:true,childList:true});reveal();
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').trim();if(t==='ACC')notify('ORDER APPROVED','Transaksi berhasil disetujui.');else if(t==='Tolak')notify('ORDER REJECTED','Pesanan ditolak.');else if(t==='Lihat Profil')notify('MEMBER DOSSIER','Membuka profil anggota Cassano.');else if(/Buka Brangkas/i.test(t))notify('BRANKAS','Membuka brankas internal.');else if(/Lihat Pesanan/i.test(t))notify('ORDERS','Membuka daftar pesanan.');});
})();
