// Cassano Sales: show clear Rupiah totals and approved sales breakdown.
async function salesPage(){
  try{
    const approved=(orders||[]).filter(o=>o.status==='Approved');
    const total=approved.reduce((sum,o)=>sum+Number(o.total||0),0);
    const latest=approved.slice(0,12);
    $('sales').innerHTML=`<div class="section"><div><h2>Penjualan</h2><small>Total transaksi yang sudah disetujui.</small></div></div><div class="stats"><div class="card salesTotalCard"><small>💰 TOTAL PENJUALAN</small><strong>${money(total)}</strong><span style="display:block;color:#8d95a3;font-size:12px;margin-top:7px">Nominal penjualan disetujui</span></div><div class="card"><small>🧾 TRANSAKSI DISETUJUI</small><strong>${approved.length}</strong><span style="display:block;color:#8d95a3;font-size:12px;margin-top:7px">Pesanan selesai diproses</span></div><div class="card"><small>📈 RATA-RATA TRANSAKSI</small><strong>${money(approved.length?total/approved.length:0)}</strong><span style="display:block;color:#8d95a3;font-size:12px;margin-top:7px">Rata-rata nilai order</span></div><div class="card"><small>🕒 TRANSAKSI TERAKHIR</small><strong>${latest.length?money(latest[0].total):money(0)}</strong><span style="display:block;color:#8d95a3;font-size:12px;margin-top:7px">${latest.length?latest[0].order_no:'Belum ada transaksi'}</span></div></div><div class="panel" style="margin-top:14px"><div class="section" style="margin-bottom:8px"><h3>Riwayat Penjualan</h3><b class="salesGrandTotal">${money(total)}</b></div><table><thead><tr><th>Tanggal</th><th>Order</th><th>Pembeli</th><th>Disetujui Oleh</th><th>Total</th><th>Nota</th></tr></thead><tbody>${latest.map(o=>`<tr><td>${o.created_at?new Date(o.created_at).toLocaleString('id-ID'):'-'}</td><td><b>${o.order_no}</b></td><td>${o.requester}</td><td>${o.approver||'-'}</td><td><b>${money(o.total)}</b></td><td><button class="primary" onclick="receiptModal(${o.id})">🧾 Nota</button></td></tr>`).join('')||'<tr><td colspan="6">Belum ada penjualan yang disetujui.</td></tr>'}</tbody></table></div>`;
  }catch(e){$('sales').innerHTML=`<div class="panel">${e.message}</div>`}
}
