// Setoran export branding + WIB campaign checks
const express=require('express');
const path=require('path');
const bcrypt=require('bcryptjs');
const session=require('express-session');
const multer=require('multer');
const {Pool}=require('pg');
const XLSX=require('xlsx');
const ExcelJS=require('exceljs');
const app=express();app.set('trust proxy',1);const PORT=process.env.PORT||3000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false,max:5});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const perms=["dashboard","items","items_manage","cart","order","orders","approve","history","stock","roles","users","roles_manage","setoran","setoran_manage"];
const schema=`
CREATE TABLE IF NOT EXISTS roles(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL,description TEXT DEFAULT '',permissions JSONB NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role_id INTEGER REFERENCES roles(id),active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS categories(id SERIAL PRIMARY KEY,name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS items(id SERIAL PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,category_id INTEGER REFERENCES categories(id),price NUMERIC(14,2) DEFAULT 0,stock INTEGER DEFAULT 0,description TEXT DEFAULT '',image TEXT);
CREATE TABLE IF NOT EXISTS cart(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,qty INTEGER NOT NULL,UNIQUE(user_id,item_id));
CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,order_no TEXT UNIQUE NOT NULL,user_id INTEGER REFERENCES users(id),status TEXT NOT NULL,total NUMERIC(14,2),approved_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS order_items(id SERIAL PRIMARY KEY,order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,item_id INTEGER REFERENCES items(id),qty INTEGER NOT NULL,price NUMERIC(14,2) NOT NULL);
CREATE TABLE IF NOT EXISTS movements(id SERIAL PRIMARY KEY,item_id INTEGER REFERENCES items(id),type TEXT NOT NULL,qty INTEGER NOT NULL,user_id INTEGER REFERENCES users(id),reference TEXT,note TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS vault(id INTEGER PRIMARY KEY DEFAULT 1,balance NUMERIC(16,2) NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS vault_transactions(id SERIAL PRIMARY KEY,type TEXT NOT NULL CHECK(type IN ('IN','OUT')),amount NUMERIC(16,2) NOT NULL CHECK(amount>0),balance_after NUMERIC(16,2) NOT NULL,user_id INTEGER REFERENCES users(id),note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS setoran_campaigns(id SERIAL PRIMARY KEY,name TEXT NOT NULL,frequency TEXT NOT NULL CHECK(frequency IN ('DAILY','WEEKLY','MONTHLY')),start_date DATE NOT NULL,end_date DATE NOT NULL,notes TEXT DEFAULT '',created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT NOW(),active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS setoran_items(id SERIAL PRIMARY KEY,campaign_id INTEGER NOT NULL REFERENCES setoran_campaigns(id) ON DELETE CASCADE,name TEXT NOT NULL,target NUMERIC(14,2) NOT NULL DEFAULT 0,target_mode TEXT NOT NULL DEFAULT 'SHARED' CHECK(target_mode IN ('SHARED','PER_MEMBER')),sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS setoran_members(id SERIAL PRIMARY KEY,campaign_id INTEGER NOT NULL REFERENCES setoran_campaigns(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,UNIQUE(campaign_id,user_id));
CREATE TABLE IF NOT EXISTS setoran_target_overrides(id SERIAL PRIMARY KEY,item_id INTEGER NOT NULL REFERENCES setoran_items(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,target NUMERIC(14,2) NOT NULL,UNIQUE(item_id,user_id));
CREATE TABLE IF NOT EXISTS setoran_transactions(id SERIAL PRIMARY KEY,campaign_id INTEGER NOT NULL REFERENCES setoran_campaigns(id) ON DELETE CASCADE,item_id INTEGER NOT NULL REFERENCES setoran_items(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,quantity NUMERIC(14,2) NOT NULL CHECK(quantity>0),note TEXT DEFAULT '',created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_setoran_tx_campaign ON setoran_transactions(campaign_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_setoran_tx_member_item ON setoran_transactions(campaign_id,user_id,item_id);
`;
async function q(sql,params=[]){return (await pool.query(sql,params)).rows}async function one(sql,params=[]){return (await pool.query(sql,params)).rows[0]}async function run(sql,params=[]){return pool.query(sql,params)}
async function init(){await pool.query(schema);
if(!(await one('SELECT id FROM roles LIMIT 1'))){for(const [name,description,permissions] of [["Bos","Akses penuh",perms],["Consigliere","Inventory dan approval",["dashboard","items","items_manage","cart","order","orders","approve","history","stock"]],["Fixer","Membuat pesanan",["dashboard","items","cart","order","history"]]])await run('INSERT INTO roles(name,description,permissions) VALUES($1,$2,$3)',[name,description,JSON.stringify(permissions)])}
for(const x of ["Dokumen","Elektronik","Akses","Operasional"])await run('INSERT INTO categories(name) VALUES($1) ON CONFLICT(name) DO NOTHING',[x]);
if(!(await one('SELECT id FROM users LIMIT 1'))){const bos=(await one("SELECT id FROM roles WHERE name='Bos'"))?.id;await run('INSERT INTO users(name,email,password,role_id) VALUES($1,$2,$3,$4)',["Bos Cassano","bos@cassano.local",bcrypt.hashSync("bos123",10),bos]);const cat=(await one("SELECT id FROM categories WHERE name='Dokumen'"))?.id;await run('INSERT INTO items(code,name,category_id,price,stock,description) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(code) DO NOTHING',["BRG-001","Dokumen Kontrak",cat,150000,12,"Dokumen operasional"])}
await run('INSERT INTO vault(id,balance) VALUES(1,0) ON CONFLICT(id) DO NOTHING');
const bosRole=await one("SELECT id FROM roles WHERE name='Bos'");
if(bosRole)await run("UPDATE roles SET permissions=permissions || '[\"setoran\",\"setoran_manage\"]'::jsonb WHERE id=$1",[bosRole.id]);
const conRole=await one("SELECT id FROM roles WHERE name='Consigliere'");
if(conRole)await run("UPDATE roles SET permissions=permissions || '[\"setoran\",\"setoran_manage\"]'::jsonb WHERE id=$1",[conRole.id]);
await run(`UPDATE items i SET stock=x.net_stock FROM (SELECT item_id,SUM(CASE WHEN type='IN' THEN qty WHEN type='OUT' THEN -qty ELSE 0 END)::int net_stock FROM movements GROUP BY item_id) x WHERE i.id=x.item_id AND i.stock=0 AND x.net_stock>0`);
}
app.use(express.json({limit:'10mb'}));app.use(express.urlencoded({extended:true}));app.use(session({secret:process.env.SESSION_SECRET||'CHANGE_ME',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));app.use(express.static(__dirname));
const imageData=req=>req.file?`data:${req.file.mimetype};base64,${req.file.buffer.toString('base64')}`:null;
async function me(req){if(!req.session.user)return null;return one('SELECT u.*,r.name role,r.permissions FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=$1',[req.session.user.id])}
async function auth(req,res,next){try{const u=await me(req);if(!u)return res.status(401).json({error:'Belum login'});if(!u.active)return res.status(403).json({error:'Akun nonaktif'});req.me=u;next()}catch(e){res.status(500).json({error:e.message})}}
function has(u,p){return Array.isArray(u.permissions)?u.permissions.includes(p):JSON.parse(u.permissions||'[]').includes(p)}function need(p){return (req,res,next)=>{if(!has(req.me,p))return res.status(403).json({error:'Role tidak memiliki akses: '+p});next()}}function vaultCanEdit(req){return req.me.role==='Bos'||req.me.role==='Consigliere'}
app.post('/api/login',async(req,res)=>{try{const u=await one('SELECT * FROM users WHERE email=$1',[req.body.email]);if(!u||!bcrypt.compareSync(req.body.password,u.password))return res.status(401).json({error:'Email atau password salah'});if(!u.active)return res.status(403).json({error:'Akun nonaktif'});req.session.user={id:u.id};req.session.save(err=>{if(err)return res.status(500).json({error:'Gagal menyimpan sesi'});res.json({ok:true})})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get('/health',(req,res)=>res.json({ok:true,service:'inventory-cassano',database:'postgresql'}));app.get('/api/me',auth,async(req,res)=>res.json({id:req.me.id,name:req.me.name,email:req.me.email,role:req.me.role,permissions:req.me.permissions}));
app.get('/api/items',auth,async(req,res)=>res.json(await q('SELECT i.*,c.name category FROM items i LEFT JOIN categories c ON c.id=i.category_id ORDER BY i.id DESC')));app.get('/api/categories',auth,async(req,res)=>res.json(await q('SELECT * FROM categories ORDER BY name'));
app.post('/api/items',auth,need('items_manage'),upload.single('photo'),async(req,res)=>{try{const b=req.body;const r=await one('INSERT INTO items(code,name,category_id,price,stock,description,image) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[b.code,b.name,b.category_id||null,+b.price||0,+b.stock||0,b.description||'',imageData(req)]);res.json({id:r.id})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/items/:id',auth,need('items_manage'),upload.single('photo'),async(req,res)=>{try{const old=await one('SELECT * FROM items WHERE id=$1',[req.params.id]);if(!old)return res.status(404).json({error:'Barang tidak ditemukan'});const b=req.body;await run('UPDATE items SET code=$1,name=$2,category_id=$3,price=$4,description=$5,image=$6 WHERE id=$7',[b.code,b.name,b.category_id||null,+b.price||0,b.description||'',imageData(req)||old.image||null,req.params.id]);res.json({ok:true,stock:old.stock})}catch(e){res.status(400).json({error:e.message})}});app.delete('/api/items/:id',auth,need('items_manage'),async(req,res)=>{await run('DELETE FROM items WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.get('/api/cart',auth,async(req,res)=>res.json(await q('SELECT c.*,i.name,i.price,i.stock,i.image FROM cart c JOIN items i ON i.id=c.item_id WHERE c.user_id=$1',[req.me.id])));app.post('/api/cart',auth,need('order'),async(req,res)=>{const old=await one('SELECT * FROM cart WHERE user_id=$1 AND item_id=$2',[req.me.id,req.body.item_id]);if(old)await run('UPDATE cart SET qty=$1 WHERE id=$2',[old.qty+(+req.body.qty||1),old.id]);else await run('INSERT INTO cart(user_id,item_id,qty) VALUES($1,$2,$3)',[req.me.id,req.body.item_id,+req.body.qty||1]);res.json({ok:true})});app.put('/api/cart/:id',auth,need('order'),async(req,res)=>{if(+req.body.qty<=0)await run('DELETE FROM cart WHERE id=$1 AND user_id=$2',[req.params.id,req.me.id]);else await run('UPDATE cart SET qty=$1 WHERE id=$2 AND user_id=$3',[+req.body.qty,req.params.id,req.me.id]);res.json({ok:true})});
app.post('/api/orders',auth,need('order'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const cart=(await client.query('SELECT c.*,i.name,i.price,i.stock FROM cart c JOIN items i ON i.id=c.item_id WHERE c.user_id=$1 FOR UPDATE',[req.me.id])).rows;if(!cart.length)throw new Error('Keranjang kosong');for(const x of cart)if(x.qty>x.stock)throw new Error('Stok '+x.name+' tidak cukup');const total=cart.reduce((s,x)=>s+x.qty*Number(x.price),0);const no='ORD-'+Date.now().toString(36).toUpperCase();const o=(await client.query('INSERT INTO orders(order_no,user_id,status,total) VALUES($1,$2,$3,$4) RETURNING id',[no,req.me.id,'Pending',total])).rows[0];for(const x of cart)await client.query('INSERT INTO order_items(order_id,item_id,qty,price) VALUES($1,$2,$3,$4)',[o.id,x.item_id,x.qty,x.price]);await client.query('DELETE FROM cart WHERE user_id=$1',[req.me.id]);await client.query('COMMIT');res.json({ok:true,order_no:no})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
async function orderList(){return q(`SELECT o.*,COALESCE(u.name,'User dihapus') requester,a.name approver,COALESCE((SELECT string_agg(i.name||' × '||oi.qty, ', ') FROM order_items oi JOIN items i ON i.id=oi.item_id WHERE oi.order_id=o.id),'') details FROM orders o LEFT JOIN users u ON u.id=o.user_id LEFT JOIN users a ON a.id=o.approved_by ORDER BY o.id DESC`)}app.get('/api/orders',auth,async(req,res)=>{const rows=await orderList();res.json(rows.filter(o=>has(req.me,'orders')||o.user_id===req.me.id))});
app.post('/api/orders/:id/approve',auth,need('approve'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const o=(await client.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!o||o.status!=='Pending')throw new Error('Pesanan sudah diproses');const its=(await client.query('SELECT * FROM order_items WHERE order_id=$1',[o.id])).rows;for(const x of its){const i=(await client.query('SELECT * FROM items WHERE id=$1 FOR UPDATE',[x.item_id])).rows[0];if(!i||i.stock<x.qty)throw new Error('Stok tidak cukup')}for(const x of its){await client.query('UPDATE items SET stock=stock-$1 WHERE id=$2',[x.qty,x.item_id]);await client.query('INSERT INTO movements(item_id,type,qty,user_id,reference) VALUES($1,$2,$3,$4,$5)',[x.item_id,'OUT',x.qty,req.me.id,o.order_no])}await client.query("UPDATE orders SET status='Approved',approved_by=$1 WHERE id=$2",[req.me.id,o.id]);await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});app.post('/api/orders/:id/reject',auth,need('approve'),async(req,res)=>{await run("UPDATE orders SET status='Rejected',approved_by=$1 WHERE id=$2 AND status='Pending'",[req.me.id,req.params.id]);res.json({ok:true})});
app.get('/api/movements',auth,need('stock'),async(req,res)=>res.json(await q('SELECT m.*,i.name item,u.name user FROM movements m JOIN items i ON i.id=m.item_id LEFT JOIN users u ON u.id=m.user_id ORDER BY m.id DESC')));app.post('/api/stock-in',auth,need('stock'),async(req,res)=>{const n=parseInt(req.body.qty,10),itemId=parseInt(req.body.item_id,10);if(!Number.isInteger(n)||n<=0)return res.status(400).json({error:'Jumlah tidak valid'});if(!Number.isInteger(itemId))return res.status(400).json({error:'Barang tidak valid'});const client=await pool.connect();try{await client.query('BEGIN');const item=(await client.query('SELECT stock FROM items WHERE id=$1 FOR UPDATE',[itemId])).rows[0];if(!item)throw new Error('Barang tidak ditemukan');const updated=(await client.query('UPDATE items SET stock=COALESCE(stock,0)+$1 WHERE id=$2 RETURNING stock',[n,itemId])).rows[0];await client.query('INSERT INTO movements(item_id,type,qty,user_id,note) VALUES($1,$2,$3,$4,$5)',[itemId,'IN',n,req.me.id,req.body.note||'']);await client.query('COMMIT');res.json({ok:true,stock:updated.stock})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/roles',auth,need('roles'),async(req,res)=>res.json(await q('SELECT * FROM roles ORDER BY id')));app.post('/api/roles',auth,need('roles_manage'),async(req,res)=>{try{await run('INSERT INTO roles(name,description,permissions) VALUES($1,$2,$3)',[req.body.name,req.body.description||'',JSON.stringify(req.body.permissions||[])]);res.json({ok:true})}catch(e){res.status(400).json({error:'Nama role sudah digunakan'})}});app.put('/api/roles/:id',auth,need('roles_manage'),async(req,res)=>{await run('UPDATE roles SET name=$1,description=$2,permissions=$3 WHERE id=$4',[req.body.name,req.body.description||'',JSON.stringify(req.body.permissions||[]),req.params.id]);res.json({ok:true})});
app.get('/api/users',auth,need('users'),async(req,res)=>res.json(await q('SELECT u.id,u.name,u.email,u.active,r.name role,u.role_id FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.id DESC')));app.post('/api/users',auth,need('users'),async(req,res)=>{try{const pass=req.body.password||'cassano123';await run('INSERT INTO users(name,email,password,role_id) VALUES($1,$2,$3,$4)',[req.body.name,req.body.email,bcrypt.hashSync(pass,10),req.body.role_id]);res.json({ok:true,temporary_password:pass})}catch(e){res.status(400).json({error:'Email sudah digunakan'})}});app.put('/api/users/:id',auth,need('users'),async(req,res)=>{await run('UPDATE users SET name=$1,role_id=$2,active=$3 WHERE id=$4',[req.body.name,req.body.role_id,!!+req.body.active,req.params.id]);res.json({ok:true})});
app.delete('/api/users/:id',auth,need('users'),async(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({error:'ID user tidak valid'});if(id===req.me.id)return res.status(400).json({error:'Tidak dapat menghapus akun yang sedang digunakan'});const client=await pool.connect();try{await client.query('BEGIN');const u=(await client.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!u)throw new Error('User tidak ditemukan');await client.query('DELETE FROM cart WHERE user_id=$1',[id]);await client.query('UPDATE orders SET user_id=NULL WHERE user_id=$1',[id]);await client.query('UPDATE orders SET approved_by=NULL WHERE approved_by=$1',[id]);await client.query('UPDATE movements SET user_id=NULL WHERE user_id=$1',[id]);await client.query('UPDATE vault_transactions SET user_id=NULL WHERE user_id=$1',[id]);await client.query('DELETE FROM users WHERE id=$1',[id]);await client.query('COMMIT');res.json({ok:true})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/vault',auth,async(req,res)=>{const v=await one('SELECT * FROM vault WHERE id=1');const tx=await q('SELECT t.*,u.name user FROM vault_transactions t LEFT JOIN users u ON u.id=t.user_id ORDER BY t.id DESC LIMIT 100');res.json({balance:v?.balance||0,updated_at:v?.updated_at||null,can_edit:vaultCanEdit(req),transactions:tx})});
app.post('/api/vault/adjust',auth,async(req,res)=>{if(!vaultCanEdit(req))return res.status(403).json({error:'Hanya Bos dan Consigliere yang dapat mengubah brangkas'});const type=req.body.type,amount=Number(req.body.amount);if(!['IN','OUT'].includes(type)||!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Transaksi tidak valid'});const client=await pool.connect();try{await client.query('BEGIN');const v=(await client.query('SELECT * FROM vault WHERE id=1 FOR UPDATE')).rows[0];const current=Number(v?.balance||0),next=type==='IN'?current+amount:current-amount;if(next<0)throw new Error('Saldo brangkas tidak mencukupi');const nv=(await client.query('UPDATE vault SET balance=$1,updated_at=NOW() WHERE id=1 RETURNING *',[next])).rows[0];await client.query('INSERT INTO vault_transactions(type,amount,balance_after,user_id,note) VALUES($1,$2,$3,$4,$5)',[type,amount,next,req.me.id,req.body.note||'']);await client.query('COMMIT');res.json({ok:true,balance:nv.balance})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});

function setoranManage(req){return has(req.me,'setoran_manage')}
function setoranAccess(req){return has(req.me,'setoran')||setoranManage(req)}
function setoranDateOk(c){const now=new Date();const jakarta=new Date(now.getTime()+7*60*60*1000);const today=jakarta.toISOString().slice(0,10);const iso=v=>String(v).slice(0,10);return today>=iso(c.start_date)&&today<=iso(c.end_date)}
async function setoranDetail(id){
  const c=await one('SELECT c.*,u.name creator FROM setoran_campaigns c LEFT JOIN users u ON u.id=c.created_by WHERE c.id=$1',[id]);
  if(!c)return null;
  const members=await q('SELECT sm.user_id,u.name,u.email FROM setoran_members sm JOIN users u ON u.id=sm.user_id WHERE sm.campaign_id=$1 ORDER BY u.name',[id]);
  const items=await q('SELECT * FROM setoran_items WHERE campaign_id=$1 ORDER BY sort_order,id',[id]);
  const overrides=await q('SELECT sto.item_id,sto.user_id,sto.target FROM setoran_target_overrides sto JOIN setoran_items si ON si.id=sto.item_id WHERE si.campaign_id=$1',[id]);
  const tx=await q('SELECT t.*,u.name user,cb.name created_by_name,si.name item_name FROM setoran_transactions t JOIN users u ON u.id=t.user_id JOIN setoran_items si ON si.id=t.item_id LEFT JOIN users cb ON cb.id=t.created_by WHERE t.campaign_id=$1 ORDER BY t.created_at DESC,t.id DESC',[id]);
  return {campaign:c,members,items,overrides,transactions:tx};
}
app.get('/api/setoran/campaigns',auth,async(req,res)=>{if(!setoranAccess(req))return res.status(403).json({error:'Role tidak memiliki akses Setoran'});res.json(await q('SELECT c.*,u.name creator,(SELECT COUNT(*)::int FROM setoran_members sm WHERE sm.campaign_id=c.id) member_count,(SELECT COUNT(*)::int FROM setoran_items si WHERE si.campaign_id=c.id) item_count FROM setoran_campaigns c LEFT JOIN users u ON u.id=c.created_by ORDER BY c.start_date DESC,c.id DESC'))});
app.get('/api/setoran/campaigns/:id',auth,async(req,res)=>{if(!setoranAccess(req))return res.status(403).json({error:'Role tidak memiliki akses Setoran'});const d=await setoranDetail(req.params.id);if(!d)return res.status(404).json({error:'Campaign tidak ditemukan'});res.json(d)});
app.post('/api/setoran/campaigns',auth,async(req,res)=>{
  if(!setoranManage(req))return res.status(403).json({error:'Hanya role yang memiliki permission setoran_manage yang dapat membuat campaign'});
  const b=req.body||{},members=Array.isArray(b.members)?[...new Set(b.members.map(Number).filter(Number.isInteger))]:[],items=Array.isArray(b.items)?b.items:[];
  if(!b.name||!['DAILY','WEEKLY','MONTHLY'].includes(b.frequency)||!b.start_date||!b.end_date||new Date(b.start_date)>new Date(b.end_date))return res.status(400).json({error:'Data campaign tidak valid'});
  if(!members.length)return res.status(400).json({error:'Pilih minimal satu member'});
  if(!items.length)return res.status(400).json({error:'Tambahkan minimal satu barang setoran'});
  const client=await pool.connect();try{await client.query('BEGIN');
    const c=(await client.query('INSERT INTO setoran_campaigns(name,frequency,start_date,end_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[b.name,b.frequency,b.start_date,b.end_date,b.notes||'',req.me.id])).rows[0];
    for(const uid of members){if(!(await client.query('SELECT id FROM users WHERE id=$1',[uid])).rows[0])throw new Error('Member tidak ditemukan: '+uid);await client.query('INSERT INTO setoran_members(campaign_id,user_id) VALUES($1,$2)',[c.id,uid])}
    let order=0;for(const it of items){const target=Number(it.target),mode=it.mode||it.target_mode||'SHARED';if(!it.name||!Number.isFinite(target)||target<0||!['SHARED','PER_MEMBER'].includes(mode))throw new Error('Barang setoran tidak valid');await client.query('INSERT INTO setoran_items(campaign_id,name,target,target_mode,sort_order) VALUES($1,$2,$3,$4,$5)',[c.id,String(it.name).trim(),target,mode,order++])}
    await client.query('COMMIT');res.json({ok:true,id:c.id});
  }catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}
});
app.put('/api/setoran/campaigns/:id',auth,async(req,res)=>{if(!setoranManage(req))return res.status(403).json({error:'Tidak memiliki permission setoran_manage'});const b=req.body||{};if(!b.name||!['DAILY','WEEKLY','MONTHLY'].includes(b.frequency)||!b.start_date||!b.end_date)return res.status(400).json({error:'Data campaign tidak valid'});await run('UPDATE setoran_campaigns SET name=$1,frequency=$2,start_date=$3,end_date=$4,notes=$5,active=$6 WHERE id=$7',[b.name,b.frequency,b.start_date,b.end_date,b.notes||'',b.active!==false,req.params.id]);res.json({ok:true})});
app.post('/api/setoran/campaigns/:id/items',auth,async(req,res)=>{if(!setoranManage(req))return res.status(403).json({error:'Tidak memiliki permission setoran_manage'});const b=req.body||{},target=Number(b.target),cid=Number(req.params.id);if(!b.name||!Number.isFinite(target)||target<0||!['SHARED','PER_MEMBER'].includes(b.target_mode))return res.status(400).json({error:'Data jenis setoran tidak valid'});const c=await one('SELECT id FROM setoran_campaigns WHERE id=$1',[cid]);if(!c)return res.status(404).json({error:'Campaign tidak ditemukan'});const max=await one('SELECT COALESCE(MAX(sort_order),0)+1 n FROM setoran_items WHERE campaign_id=$1',[cid]);const r=await one('INSERT INTO setoran_items(campaign_id,name,target,target_mode,sort_order) VALUES($1,$2,$3,$4,$5) RETURNING id',[cid,String(b.name).trim(),target,b.target_mode,Number(max.n)]);res.json({ok:true,id:r.id})});
app.delete('/api/setoran/items/:id',auth,async(req,res)=>{if(!setoranManage(req))return res.status(403).json({error:'Tidak memiliki permission setoran_manage'});const id=Number(req.params.id);const item=await one('SELECT id,name FROM setoran_items WHERE id=$1',[id]);if(!item)return res.status(404).json({error:'Jenis setoran tidak ditemukan'});const tx=await one('SELECT id FROM setoran_transactions WHERE item_id=$1 LIMIT 1',[id]);if(tx)return res.status(400).json({error:'Jenis setoran sudah memiliki riwayat setoran, tidak bisa dihapus agar histori tetap aman'});await run('DELETE FROM setoran_items WHERE id=$1',[id]);res.json({ok:true})});app.put('/api/setoran/items/:id',auth,async(req,res)=>{if(!setoranManage(req))return res.status(403).json({error:'Tidak memiliki permission setoran_manage'});const b=req.body||{},target=Number(b.target);if(!b.name||!Number.isFinite(target)||target<0||!['SHARED','PER_MEMBER'].includes(b.target_mode))return res.status(400).json({error:'Data target tidak valid'});await run('UPDATE setoran_items SET name=$1,target=$2,target_mode=$3 WHERE id=$4',[String(b.name).trim(),target,b.target_mode,req.params.id]);res.json({ok:true})});
app.put('/api/setoran/items/:id/target/:userId',auth,async(req,res)=>{if(!setoranManage(req))return res.status(403).json({error:'Tidak memiliki permission setoran_manage'});const target=Number(req.body?.target);if(!Number.isFinite(target)||target<0)return res.status(400).json({error:'Target tidak valid'});await run('INSERT INTO setoran_target_overrides(item_id,user_id,target) VALUES($1,$2,$3) ON CONFLICT(item_id,user_id) DO UPDATE SET target=EXCLUDED.target',[req.params.id,req.params.userId,target]);res.json({ok:true})});
app.post('/api/setoran/campaigns/:id/transactions',auth,async(req,res)=>{
  if(!setoranAccess(req))return res.status(403).json({error:'Tidak memiliki permission setoran'});
  const cid=Number(req.params.id),itemId=Number(req.body?.item_id),qty=Number(req.body?.quantity),requestedUser=Number(req.body?.user_id);
  if(!Number.isInteger(cid)||cid<=0||!Number.isInteger(itemId)||itemId<=0||!Number.isFinite(qty)||qty<=0)return res.status(400).json({error:'Data setoran tidak valid'});
  const c=await one('SELECT * FROM setoran_campaigns WHERE id=$1',[cid]);if(!c)return res.status(404).json({error:'Campaign tidak ditemukan'});
  const today=await one("SELECT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Jakarta')::date AS d");if(today.d<c.start_date||today.d>c.end_date)return res.status(400).json({error:'Campaign sedang tidak aktif pada tanggal ini'});
  const item=await one('SELECT * FROM setoran_items WHERE id=$1 AND campaign_id=$2',[itemId,cid]);if(!item)return res.status(404).json({error:'Jenis setoran tidak ditemukan'});
  const uid=setoranManage(req)&&Number.isInteger(requestedUser)&&requestedUser>0?requestedUser:req.me.id;
  if(!(await one('SELECT id FROM setoran_members WHERE campaign_id=$1 AND user_id=$2',[cid,uid])))return res.status(403).json({error:'Member tersebut belum dimasukkan ke campaign'});
  await run('INSERT INTO setoran_transactions(campaign_id,item_id,user_id,quantity,note,created_by) VALUES($1,$2,$3,$4,$5,$6)',[cid,itemId,uid,qty,req.body?.note||'',req.me.id]);res.json({ok:true})
});
app.get('/api/setoran/campaigns/:id/export',auth,async(req,res)=>{
  try{
    if(!setoranAccess(req))return res.status(403).json({error:'Tidak memiliki permission setoran'});
    const d=await setoranDetail(req.params.id); if(!d)return res.status(404).json({error:'Campaign tidak ditemukan'});
    const {campaign:c}=d,tx=Array.isArray(d.transactions)?d.transactions:[],its=Array.isArray(d.items)?d.items:[],mem=Array.isArray(d.members)?d.members:[],ovs=Array.isArray(d.overrides)?d.overrides:[];
    const ov=(itemId,userId)=>{const x=ovs.find(o=>Number(o.item_id)===Number(itemId)&&Number(o.user_id)===Number(userId));return x?Number(x.target):null};
    const totalFor=(itemId,userId)=>tx.filter(t=>Number(t.item_id)===Number(itemId)&&Number(t.user_id)===Number(userId)).reduce((a,t)=>a+Number(t.quantity||0),0);
    const sharedTotal=itemId=>tx.filter(t=>Number(t.item_id)===Number(itemId)).reduce((a,t)=>a+Number(t.quantity||0),0);
    const targetFor=(item,userId)=>item.target_mode==='SHARED'?Number(item.target):Number(ov(item.id,userId)??item.target);
    const fmtDate=v=>{const x=String(v||'').slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(x)){const [y,m,dd]=x.split('-');return dd+'/'+m+'/'+y}return x||'-'};
    const wb=new ExcelJS.Workbook();wb.creator='Inventory Cassano';wb.created=new Date();wb.modified=new Date();
    const colLetter=n=>{let x=n,r='';while(x){const m=(x-1)%26;r=String.fromCharCode(65+m)+r;x=Math.floor((x-1)/26)}return r};
    const dataLast=2+its.length+1, summaryStart=dataLast+2, lastCol=Math.max(dataLast+2,summaryStart+1), titleEnd=colLetter(lastCol);
    const ws=wb.addWorksheet('Setoran',{views:[{state:'frozen',ySplit:8}]});
    ws.mergeCells('A1:B3');ws.mergeCells('C1:'+titleEnd+'1');ws.mergeCells('C2:'+titleEnd+'3');
    ws.getCell('C1').value='CASSANO';ws.getCell('C1').font={bold:true,size:14,color:{argb:'FFFFFFFF'}};ws.getCell('C1').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF111111'}};ws.getCell('C1').alignment={horizontal:'center',vertical:'middle'};
    ws.getCell('C2').value='DATA SETORAN '+String(c.name||'').toUpperCase();ws.getCell('C2').font={bold:true,size:20,color:{argb:'FFFFFFFF'}};ws.getCell('C2').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF111111'}};ws.getCell('C2').alignment={horizontal:'center',vertical:'middle',wrapText:true};
    try{const lr=await fetch('https://raw.githubusercontent.com/ilmis6471-web/inventory_cassano/main/logo.png');if(lr.ok){const lb=Buffer.from(await lr.arrayBuffer());const id=wb.addImage({buffer:lb,extension:'png'});ws.addImage(id,{tl:{col:0.12,row:0.12},ext:{width:92,height:92}})}}catch(e){console.warn('SETORAN_LOGO_SKIP',e.message)}
    ws.mergeCells('A4:B4');ws.getCell('A4').value='Periode';ws.getCell('C4').value=fmtDate(c.start_date)+' - '+fmtDate(c.end_date);
    ws.mergeCells('A5:B5');ws.getCell('A5').value='Frekuensi';ws.getCell('C5').value=({DAILY:'Harian',WEEKLY:'Mingguan',MONTHLY:'Bulanan'})[c.frequency]||c.frequency||'-';
    [4,5].forEach(r=>{ws.getCell('A'+r).font={bold:true};ws.getCell('A'+r).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE8E8E8'}}});
    const headerRow=8,headers=['No','Nama',...its.map(i=>i.name||'-'),'Status'];headers.forEach((v,i)=>{const cell=ws.getRow(headerRow).getCell(i+1);cell.value=v;cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF7A1824'}};cell.alignment={horizontal:'center',vertical:'middle',wrapText:true};cell.border={top:{style:'thin'},left:{style:'thin'},bottom:{style:'thin'},right:{style:'thin'}}});
    mem.forEach((m,i)=>{const vals=its.map(it=>totalFor(it.id,m.user_id));const statuses=its.map((it,j)=>{const val=it.target_mode==='SHARED'?sharedTotal(it.id):vals[j],tar=targetFor(it,m.user_id);return val<=0?'Belum Ada Setoran':val>=tar?'Target Tercapai':'Target Belum Tercapai'});const status=statuses.length&&statuses.every(x=>x==='Target Tercapai')?'Target Tercapai':statuses.length&&statuses.every(x=>x==='Belum Ada Setoran')?'Belum Ada Setoran':'Target Belum Tercapai';[i+1,m.name||'-',...vals,status].forEach((v,j)=>{const cell=ws.getRow(headerRow+1+i).getCell(j+1);cell.value=v;cell.alignment={vertical:'middle',wrapText:true};cell.border={top:{style:'thin'},left:{style:'thin'},bottom:{style:'thin'},right:{style:'thin'}};if(j>=2&&j<2+its.length)cell.numFmt='#,##0.##'});});
    const totalRow=headerRow+1+mem.length;ws.getRow(totalRow).getCell(2).value='TOTAL';its.forEach((it,j)=>ws.getRow(totalRow).getCell(3+j).value=sharedTotal(it.id));ws.getRow(totalRow).eachCell(cell=>{cell.font={bold:true};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE8E8E8'}};cell.border={top:{style:'thin'},left:{style:'thin'},bottom:{style:'thin'},right:{style:'thin'}}});
    const sCol=summaryStart,sTarget=colLetter(sCol),sProgress=colLetter(sCol+1);ws.getCell(sTarget+'4').value='TARGET';ws.getCell(sProgress+'4').value='PROGRESS';ws.getCell(sTarget+'4').font=ws.getCell(sProgress+'4').font={bold:true,color:{argb:'FFFFFFFF'}};ws.getCell(sTarget+'4').fill=ws.getCell(sProgress+'4').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF7A1824'}};its.forEach((it,j)=>{const r=5+j;ws.getCell(colLetter(sCol-1)+r).value=it.name||'-';ws.getCell(sTarget+r).value=it.target_mode==='SHARED'?Number(it.target||0):mem.reduce((sum,m)=>sum+targetFor(it,m.user_id),0);ws.getCell(sProgress+r).value=sharedTotal(it.id);ws.getCell(sTarget+r).numFmt=ws.getCell(sProgress+r).numFmt='#,##0.##';[ws.getCell(colLetter(sCol-1)+r),ws.getCell(sTarget+r),ws.getCell(sProgress+r)].forEach(cell=>{cell.border={top:{style:'thin'},left:{style:'thin'},bottom:{style:'thin'},right:{style:'thin'}}})});
    ws.columns=[{width:7},{width:28},...its.map(()=>({width:18})),{width:25},{width:20},{width:14},{width:14}];ws.getRow(1).height=22;ws.getRow(2).height=32;ws.getRow(8).height=32;
    const detail=wb.addWorksheet('Riwayat Setoran',{views:[{state:'frozen',ySplit:6}]});detail.mergeCells('A1:F3');detail.getCell('A1').value='CASSANO — RIWAYAT SETORAN';detail.getCell('A1').font={bold:true,size:18,color:{argb:'FFFFFFFF'}};detail.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF111111'}};detail.getCell('A1').alignment={horizontal:'center',vertical:'middle'};
    try{const lr=await fetch('https://raw.githubusercontent.com/ilmis6471-web/inventory_cassano/main/logo.png');if(lr.ok){const lb=Buffer.from(await lr.arrayBuffer());const id=wb.addImage({buffer:lb,extension:'png'});detail.addImage(id,{tl:{col:0.12,row:0.12},ext:{width:70,height:70}})}}catch(e){}
    ['Tanggal','Nama','Barang','Jumlah','Catatan','Dicatat Oleh'].forEach((v,i)=>{const cell=detail.getRow(6).getCell(i+1);cell.value=v;cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF7A1824'}};cell.alignment={horizontal:'center',vertical:'middle'};cell.border={top:{style:'thin'},left:{style:'thin'},bottom:{style:'thin'},right:{style:'thin'}}});
    tx.forEach((t,i)=>{[t.created_at?new Date(t.created_at):'',t.user||'-',t.item_name||'-',Number(t.quantity||0),t.note||'',t.created_by_name||'-'].forEach((v,j)=>{const cell=detail.getRow(7+i).getCell(j+1);cell.value=v;cell.border={top:{style:'thin'},left:{style:'thin'},bottom:{style:'thin'},right:{style:'thin'}};if(j===0&&v)cell.numFmt='dd/mm/yyyy hh:mm';if(j===3)cell.numFmt='#,##0.##'});});
    detail.columns=[{width:22},{width:24},{width:20},{width:14},{width:30},{width:24}];detail.getRow(1).height=30;detail.getRow(6).height=28;
    const buf=await wb.xlsx.writeBuffer(),safe=String(c.name||'campaign').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,60)||'campaign';
    res.status(200).setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').setHeader('Content-Disposition','attachment; filename="Setoran-'+safe+'.xlsx"').setHeader('Content-Length',buf.length).end(Buffer.from(buf));
  }catch(err){console.error('SETORAN_EXPORT_ERROR',err);res.status(500).json({error:'Gagal membuat Excel setoran',detail:err.message});}
});

app.get('/api/dashboard',auth,async(req,res)=>res.json({items:(await one('SELECT COUNT(*)::int n FROM items')).n,stock:(await one('SELECT COALESCE(SUM(stock),0)::int n FROM items')).n,pending:(await one("SELECT COUNT(*)::int n FROM orders WHERE status='Pending'")).n,approved:(await one("SELECT COUNT(*)::int n FROM orders WHERE status='Approved'")).n}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));init().then(()=>app.listen(PORT,()=>console.log('Inventory Cassano running on port '+PORT))).catch(e=>{console.error(e);process.exit(1)});