// Cassano Setoran Campaign System
(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const freq={DAILY:'Harian',WEEKLY:'Mingguan',MONTHLY:'Bulanan'};
  const qty=n=>Number.isInteger(Number(n))?Number(n).toLocaleString('id-ID'):Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:2});
  let campaigns=[],current=null,archiveMode='active',archiveYear='',archiveMonth='';
  const manager=()=>allow('setoran_manage');
  const status=(v,t)=>Number(v)<=0?['zero','⚪ Belum Ada Setoran']:Number(t)<=0||Number(v)>=Number(t)?['ok','🟢 Target Tercapai']:['warn','🟡 Target Belum Tercapai'];
  const total=(item,user)=>current.transactions.filter(x=>Number(x.item_id)===Number(item)&&Number(x.user_id)===Number(user)).reduce((a,x)=>a+Number(x.quantity),0);
  const shared=item=>current.transactions.filter(x=>Number(x.item_id)===Number(item)).reduce((a,x)=>a+Number(x.quantity),0);
  const target=(item,user)=>{let o=current.overrides.find(x=>Number(x.item_id)===Number(item.id)&&Number(x.user_id)===Number(user));return item.target_mode==='SHARED'?Number(item.target):Number(o?.target??item.target)};
  function css(){if($('setoranCss'))return;let s=document.createElement('style');s.id='setoranCss';s.textContent='.setHero{padding:22px;border:1px solid #3d2028;border-radius:16px;background:linear-gradient(135deg,#17171c,#260b12);margin-bottom:15px}.setHero small{color:#d72a43;font-weight:900;letter-spacing:1.5px}.setHero h2{margin:6px 0}.setHero p{color:#9299a5;margin:0}.setToolbar{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.setToolbar select{min-width:220px}.setStats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:15px 0}.setStat{padding:15px;border:1px solid #2b2e36;border-radius:13px;background:#121419}.setStat small{color:#7f8794}.setStat b{display:block;font-size:21px;margin-top:6px}.setPanel{border:1px solid #2b2e36;border-radius:14px;background:#121419;overflow:auto;margin-top:15px}.setHead{padding:14px 16px;border-bottom:1px solid #2b2e36;display:flex;justify-content:space-between;gap:10px}.setTable{width:100%;border-collapse:collapse;min-width:900px}.setTable th,.setTable td{padding:10px;border-bottom:1px solid #252830;text-align:center;white-space:nowrap}.setTable th{font-size:10px;color:#8d95a3;text-transform:uppercase}.setTable th:nth-child(2),.setTable td:nth-child(2){text-align:left;position:sticky;left:0;background:#121419}.setCell{min-width:105px}.setCell b,.setCell small{display:block}.setCell small{font-size:9px;color:#8d95a3}.setStatus{font-size:9px;font-weight:800}.setStatus.zero{color:#a7adb7}.setStatus.warn{color:#ffc05a}.setStatus.ok{color:#55d98a}.setGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:15px}.setCard{padding:16px;border:1px solid #2b2e36;border-radius:14px;background:#121419;cursor:pointer}.setCard.active{border-color:#9d2438}.setCard h3{margin:8px 0 5px}.setCard p{color:#7f8794;font-size:11px;margin:0}.setTag{display:inline-block;padding:4px 7px;border-radius:999px;background:#24151a;color:#ff7183;font-size:9px;font-weight:900}.setMembers{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;max-height:230px;overflow:auto;padding:8px;border:1px solid #2b2e36;border-radius:10px}.setMembers label{padding:7px;border:1px solid #292c33;border-radius:8px;font-size:11px}.setItemRow{display:grid;grid-template-columns:1fr 120px 140px 35px;gap:7px;margin-top:7px}.setHistory{max-height:380px;overflow:auto}.setHistoryRow{display:grid;grid-template-columns:150px 1fr 90px 1fr;gap:10px;padding:10px 0;border-bottom:1px solid #252830;font-size:11px}.setMuted{color:#7f8794}@media(max-width:850px){.setStats{grid-template-columns:1fr 1fr}.setGrid{grid-template-columns:1fr 1fr}}@media(max-width:550px){.setStats,.setGrid{grid-template-columns:1fr}.setItemRow{grid-template-columns:1fr}.setMembers{grid-template-columns:1fr}}';document.head.appendChild(s)}
  async function load(id){current=await api('/api/setoran/campaigns/'+id);render()}
  async function page(){css();try{campaigns=await api('/api/setoran/campaigns');if(campaigns.length)await load(current?.campaign?.id||campaigns[0].id);else{current=null;render()}}catch(e){$('setoran').innerHTML='<div class="panel"><b>Gagal memuat Setoran</b><p>'+esc(e.message)+'</p></div>'}}
  function render(){css();let c=current?.campaign;const now=new Date(),jakarta=new Date(now.getTime()+7*60*60*1000),today=jakarta.toISOString().slice(0,10);const isArchive=x=>String(x.end_date).slice(0,10)<today;const years=[...new Set(campaigns.map(x=>String(x.start_date).slice(0,4)))].sort().reverse();const months=['01','02','03','04','05','06','07','08','09','10','11','12'];let visibleCampaigns=campaigns.filter(x=>archiveMode==='archive'?isArchive(x):!isArchive(x));if(archiveMode==='archive'&&archiveYear)visibleCampaigns=visibleCampaigns.filter(x=>String(x.start_date).slice(0,4)===archiveYear);if(archiveMode==='archive'&&archiveMonth)visibleCampaigns=visibleCampaigns.filter(x=>String(x.start_date).slice(5,7)===archiveMonth);let h='<div class="setHero"><div class="section" style="margin:0"><div><small>SETORAN CAMPAIGN SYSTEM</small><h2>Setoran</h2><p>Campaign Harian, Mingguan, atau Bulanan. Setoran boleh berkali-kali walaupun target sudah tercapai.</p></div>'+(manager()?'<button class="primary" onclick="setoranCampaignModal()">+ Campaign Baru</button>':'')+'</div></div>';
    h+='<div class="setToolbar"><select id="setArchiveMode"><option value="active" '+(archiveMode==='active'?'selected':'')+'>Campaign Aktif</option><option value="archive" '+(archiveMode==='archive'?'selected':'')+'>Arsip Campaign</option></select>'+(archiveMode==='archive'?'<select id="setArchiveYear"><option value="">Semua Tahun</option>'+years.map(y=>'<option value="'+y+'" '+(archiveYear===y?'selected':'')+'>'+y+'</option>').join('')+'</select><select id="setArchiveMonth"><option value="">Semua Bulan</option>'+months.map((m,i)=>'<option value="'+m+'" '+(archiveMonth===m?'selected':'')+'>'+String(i+1).padStart(2,'0')+'</option>').join('')+'</select>':'')+'<select id="setCampaign"><option value="">Pilih campaign...</option>'+visibleCampaigns.map(x=>'<option value="'+x.id+'" '+(c&&Number(c.id)===Number(x.id)?'selected':'')+'>'+esc(x.name)+' • '+freq[x.frequency]+'</option>').join('')+'</select>';
    if(c)h+='<button class="btn" onclick="setoranAddModal()">+ Tambah Setoran</button><button class="btn" onclick="setoranCashModal()">$ Setoran Kas</button><button class="btn" onclick="setoranHistory()">◷ Riwayat / Koreksi</button>'+(manager()?'<button class="btn" onclick="setoranAddMember('+c.id+')">+ Tambah Member</button><button class="btn" onclick="setoranCampaignModal('+c.id+')">Edit Campaign</button>':'')+'<button class="btn" onclick="setoranExport()">📊 Export Excel</button>';
    h+='</div>';
    h+='<div class="setGrid">'+(visibleCampaigns.map(x=>'<div class="setCard '+(c&&Number(c.id)===Number(x.id)?'active':'')+'" onclick="loadSetoran('+x.id+')"><span class="setTag">'+freq[x.frequency]+'</span><h3>'+esc(x.name)+'</h3><p>'+String(x.start_date).slice(0,10)+' → '+String(x.end_date).slice(0,10)+' • '+x.member_count+' member • '+x.item_count+' jenis</p></div>').join('')||'<div class="panel">Belum ada campaign.</div>')+'</div>';
    if(!c){$('setoran').innerHTML=h;return}
    let active=today>=String(c.start_date).slice(0,10)&&today<=String(c.end_date).slice(0,10);
    h+='<div class="setStats"><div class="setStat"><small>PERIODE</small><b>'+freq[c.frequency]+'</b><span class="setMuted">'+String(c.start_date).slice(0,10)+' → '+String(c.end_date).slice(0,10)+'</span></div><div class="setStat"><small>MEMBER</small><b>'+current.members.length+'</b><span class="setMuted">Peserta</span></div><div class="setStat"><small>JENIS SETORAN</small><b>'+current.items.length+'</b><span class="setMuted">Nama barang bisa diedit</span></div><div class="setStat"><small>STATUS</small><b>'+(active?'AKTIF':'SELESAI')+'</b><span class="setMuted">'+current.transactions.length+' transaksi</span></div></div>';
    h+='<div class="setPanel"><div class="setHead"><div><b>'+esc(c.name)+'</b><div class="setMuted">'+esc(c.notes||'')+'</div></div>'+(manager()?'<button class="btn" onclick="setoranItemModal()">+ Jenis Setoran</button>':'')+'</div><table class="setTable"><thead><tr><th>No</th><th>Nama</th>'+current.items.map(i=>'<th>'+esc(i.name)+'<br><small>'+(i.target_mode==='SHARED'?'Target Bersama':'Target / Member')+' '+qty(i.target)+'</small></th>').join('')+'<th>Status</th></tr></thead><tbody>';
    current.members.forEach((m,idx)=>{let states=current.items.map(i=>{let own=total(i.id,m.user_id),v=i.target_mode==='SHARED'?shared(i.id):own,t=target(i,m.user_id),s=status(v,t);return {own,v,t,s}});let all=states.length&&states.every(x=>x.s[0]==='ok'),none=states.length&&states.every(x=>x.s[0]==='zero');h+='<tr><td>'+(idx+1)+'</td><td><b>'+esc(m.name)+'</b></td>'+states.map(x=>'<td class="setCell"><b>'+qty(x.own)+'</b><small>'+qty(x.v)+' / '+qty(x.t)+'</small><span class="setStatus '+x.s[0]+'">'+x.s[1]+'</span></td>').join('')+'<td><span class="setStatus '+(all?'ok':none?'zero':'warn')+'">'+(all?'🟢 Target Tercapai':none?'⚪ Belum Ada Setoran':'🟡 Target Belum Tercapai')+'</span></td></tr>'});
    h+='</tbody><tfoot><tr><th></th><th>TOTAL</th>'+current.items.map(i=>'<th>'+qty(shared(i.id))+'</th>').join('')+'<th></th></tr></table></div>';
    h+='<div class="setPanel"><div class="setHead"><div><b>Target Campaign</b><div class="setMuted">Bersama atau per member.</div></div></div><table class="setTable"><thead><tr><th>Barang</th><th>Mode</th><th>Target</th><th>Progress</th><th>Status</th>'+(manager()?'<th>Aksi</th>':'')+'</tr></thead><tbody>';
    current.items.forEach(i=>{let v=shared(i.id),s=status(v,i.target);h+='<tr><td style="text-align:left"><b>'+esc(i.name)+'</b></td><td>'+ (i.target_mode==='SHARED'?'Bersama':'Per Member')+'</td><td>'+qty(i.target)+'</td><td>'+qty(v)+' / '+qty(i.target)+'</td><td><span class="setStatus '+s[0]+'">'+s[1]+'</span></td>'+(manager()?'<td><button class="btn" onclick="setoranItemModal('+i.id+')">Edit</button>'+(i.target_mode==='PER_MEMBER'?'<button class="btn" onclick="setoranOverrides('+i.id+')">Target Member</button>':'')+'</td>':'')+'</tr>'});
    h+='</tbody></table></div>';
    $('setoran').innerHTML=h;$('setCampaign').onchange=e=>e.target.value&&loadSetoran(e.target.value);if($('setArchiveMode'))$('setArchiveMode').onchange=e=>{archiveMode=e.target.value;render()};if($('setArchiveYear'))$('setArchiveYear').onchange=e=>{archiveYear=e.target.value;render()};if($('setArchiveMonth'))$('setArchiveMonth').onchange=e=>{archiveMonth=e.target.value;render()};
  }
  window.setoranPage=page;window.loadSetoran=load;
  window.setoranCampaignModal=async function(id){if(!manager())return;let d=id?await api('/api/setoran/campaigns/'+id):null,c=d?.campaign,users=[];try{users=await api('/api/users')}catch{users=current?.members||[me]}
    openM(c?'Edit Campaign':'Campaign Setoran','<form id="scf"><div class="setModalGrid"><div><label>Nama Campaign</label><input id="scn" required value="'+esc(c?.name||'')+'"></div><div><label>Periode</label><select id="scfqq"><option value="DAILY" '+(c?.frequency==='DAILY'?'selected':'')+'>Harian</option><option value="WEEKLY" '+(c?.frequency==='WEEKLY'?'selected':'')+'>Mingguan</option><option value="MONTHLY" '+(c?.frequency==='MONTHLY'?'selected':'')+'>Bulanan</option></select></div><div><label>Mulai</label><input id="scs" type="date" required value="'+String(c?.start_date||'').slice(0,10)+'"></div><div><label>Berakhir</label><input id="sce" type="date" required value="'+String(c?.end_date||'').slice(0,10)+'"></div><div class="setFull"><label>Catatan</label><textarea id="scn2">'+esc(c?.notes||'')+'</textarea></div>'+(!c?'<div class="setFull"><label>Member Campaign</label><div class="setMembers">'+users.map(u=>'<label><input class="scm" type="checkbox" value="'+u.id+'"> '+esc(u.name)+'</label>').join('')+'</div></div><div class="setFull"><label>Jenis Setoran</label><div id="sib"></div><button type="button" class="btn" onclick="setoranBuilderAdd()">+ Tambah Jenis</button></div>':'<div class="setFull"><label>Member Campaign</label><div class="setMembers">' +(c?current.members.map(m=>'<label>'+esc(m.name)+'</label>').join(''):'') + '</div><button type="button" class="btn" onclick="setoranAddMember('+c.id+')">+ Tambah Member</button><div class="setMuted" style="margin-top:6px">Member baru langsung ikut campaign. Histori member lama tetap aman.</div></div>')+'<div class="modalactions setFull"><button type="button" class="btn" onclick="closeM()">Batal</button><button class="primary">'+(c?'Simpan Perubahan':'Buat Campaign')+'</button></div></div></form>');
    if(!c){window.sbr=[{name:'Ruby Bar',target:0,mode:'SHARED'}];setoranBuilderRender()}else window.sbr=[];
    $('scf').onsubmit=async e=>{e.preventDefault();try{let base={name:$('scn').value.trim(),frequency:$('scfqq').value,start_date:$('scs').value,end_date:$('sce').value,notes:$('scn2').value};if(c)await api('/api/setoran/campaigns/'+c.id,{method:'PUT',body:JSON.stringify({...base,active:true})});else{let members=[...document.querySelectorAll('.scm:checked')].map(x=>Number(x.value));if(!members.length)throw Error('Pilih minimal satu member');await api('/api/setoran/campaigns',{method:'POST',body:JSON.stringify({...base,members,items:window.sbr})})}closeM();campaigns=await api('/api/setoran/campaigns');await load(c?.id||campaigns[0].id);toast(c?'Campaign diperbarui':'Campaign berhasil dibuat')}catch(e){toast(e.message)}};
  };
  window.setoranAddMember=async function(cid){if(!manager())return;let users=[];try{users=await api('/api/users')}catch(e){return toast(e.message)}const existing=new Set((current?.members||[]).map(m=>Number(m.user_id)));const available=users.filter(u=>u.active&&!existing.has(Number(u.id)));if(!available.length)return toast('Tidak ada member aktif yang bisa ditambahkan');openM('Tambah Member ke Campaign','<form id="samf"><label>Member</label><select id="samuid" required>'+available.map(u=>'<option value="'+u.id+'">'+esc(u.name)+' — '+esc(u.email)+'</option>').join('')+'</select><div class="modalactions"><button type="button" class="btn" onclick="closeM()">Batal</button><button class="primary">Tambah Member</button></div></form>');$('samf').onsubmit=async e=>{e.preventDefault();try{await api('/api/setoran/campaigns/'+cid+'/members',{method:'POST',body:JSON.stringify({user_id:Number($('samuid').value)})});closeM();await load(cid);toast('Member berhasil ditambahkan ke campaign')}catch(x){toast(x.message)}}};window.setoranBuilderAdd=()=>{window.sbr.push({name:'',target:0,mode:'SHARED'});setoranBuilderRender()};
  function setoranBuilderRender(){let b=$('sib');if(!b)return;b.innerHTML=window.sbr.map((r,i)=>'<div class="setItemRow"><input value="'+esc(r.name)+'" placeholder="Nama barang" oninput="sbr['+i+'].name=this.value"><input type="number" min="0" step="0.01" value="'+r.target+'" oninput="sbr['+i+'].target=Number(this.value)"><select onchange="sbr['+i+'].mode=this.value"><option value="SHARED" '+(r.mode==='SHARED'?'selected':'')+'>Target bersama</option><option value="PER_MEMBER" '+(r.mode==='PER_MEMBER'?'selected':'')+'>Target / member</option></select><button type="button" class="btn" onclick="sbr.splice('+i+',1);setoranBuilderRender()">×</button></div>').join('')}
  window.setoranItemModal=async function(id){if(!manager())return;let i=id?current.items.find(x=>Number(x.id)===Number(id)):null;openM(id?'Edit Jenis Setoran':'Tambah Jenis Setoran','<form id="sif"><input id="sin" required value="'+esc(i?.name||'')+'" placeholder="Nama barang"><input id="sit" type="number" min="0" step="0.01" required value="'+(i?.target||0)+'" placeholder="Target"><select id="sim"><option value="SHARED" '+((i?.target_mode||'SHARED')==='SHARED'?'selected':'')+'>Target bersama</option><option value="PER_MEMBER" '+((i?.target_mode||'SHARED')==='PER_MEMBER'?'selected':'')+'>Target per member</option></select><div class="modalactions"><button type="button" class="btn" onclick="closeM()">Batal</button>' +(id?'<button type="button" class="btn" onclick="setoranDeleteItem('+id+')">Hapus</button>':'') + '<button class="primary">Simpan</button></div></form>');$('sif').onsubmit=async e=>{e.preventDefault();try{if(id)await api('/api/setoran/items/'+id,{method:'PUT',body:JSON.stringify({name:$('sin').value.trim(),target:Number($('sit').value),target_mode:$('sim').value})});else await api('/api/setoran/campaigns/'+current.campaign.id+'/items',{method:'POST',body:JSON.stringify({name:$('sin').value.trim(),target:Number($('sit').value),target_mode:$('sim').value})});closeM();await load(current.campaign.id);toast(id?'Jenis setoran diperbarui':'Jenis setoran ditambahkan')}catch(x){toast(x.message)}}};
  window.setoranDeleteItem=async function(id){if(!manager()||!id)return;if(!confirm('Hapus jenis setoran ini? Jika sudah ada riwayat, sistem akan menolak agar histori aman.'))return;try{await api('/api/setoran/items/'+id,{method:'DELETE'});closeM();await load(current.campaign.id);toast('Jenis setoran dihapus')}catch(e){toast(e.message)}};
  window.setoranOverrides=function(id){let i=current.items.find(x=>Number(x.id)===Number(id));openM('Target Per Member — '+esc(i.name),'<div class="setMembers">'+current.members.map(m=>'<button type="button" class="btn" onclick="setoranOverride('+i.id+','+m.user_id+')">'+esc(m.name)+' — '+qty(target(i,m.user_id))+'</button>').join('')+'</div>')};
  window.setoranOverride=function(item,user){let i=current.items.find(x=>Number(x.id)===Number(item)),m=current.members.find(x=>Number(x.user_id)===Number(user));openM('Target '+esc(m.name),'<form id="ovf"><input id="ovt" type="number" min="0" step="0.01" value="'+target(i,user)+'" required><div class="modalactions"><button type="button" class="btn" onclick="setoranOverrides('+item+')">Kembali</button><button class="primary">Simpan</button></div></form>');$('ovf').onsubmit=async e=>{e.preventDefault();try{await api('/api/setoran/items/'+item+'/target/'+user,{method:'PUT',body:JSON.stringify({target:Number($('ovt').value)})});closeM();await load(current.campaign.id);toast('Target member diperbarui')}catch(x){toast(x.message)}}};
  window.setoranAddModal=function(){let members=current.members;openM('Tambah Setoran','<form id="stf"><div class="setModalGrid"><div><label>Member</label><select id="stu" '+(manager()?'':'disabled')+'>'+members.map(m=>'<option value="'+m.user_id+'">'+esc(m.name)+'</option>').join('')+'</select></div><div><label>Barang</label><select id="sti">'+current.items.map(i=>'<option value="'+i.id+'">'+esc(i.name)+'</option>').join('')+'</select></div><div><label>Jumlah</label><input id="stq" type="number" min="0.01" step="0.01" required></div><div><label>Catatan</label><input id="stn" placeholder="Opsional"></div><div class="setFull setMuted">Target tercapai tidak mengunci setoran. Member tetap bisa setor lagi.</div><div class="modalactions setFull"><button type="button" class="btn" onclick="closeM()">Batal</button><button class="primary">Simpan Setoran</button></div></div></form>');$('stf').onsubmit=async e=>{e.preventDefault();try{await api('/api/setoran/campaigns/'+current.campaign.id+'/transactions',{method:'POST',body:JSON.stringify({user_id:Number($('stu').value),item_id:Number($('sti').value),quantity:Number($('stq').value),note:$('stn').value})});closeM();await load(current.campaign.id);toast('Setoran berhasil dicatat')}catch(x){toast(x.message)}}};
  window.setoranCashModal=function(){let members=current.members;openM('Setoran Kas','<form id="skf"><div class="setModalGrid"><div><label>Member</label><select id="sku" '+(manager()?'':'disabled')+'>'+members.map(m=>'<option value="'+m.user_id+'">'+esc(m.name)+'</option>').join('')+'</select></div><div><label>Nominal</label><input id="ska" type="number" min="0.01" step="0.01" required placeholder="Nominal $"></div><div><label>Catatan</label><input id="skn" placeholder="Opsional"></div><div class="setFull setMuted">Setoran Kas akan langsung masuk ke saldo Kas dan tercatat sebagai Uang Masuk → Setoran Kas.</div><div class="modalactions setFull"><button type="button" class="btn" onclick="closeM()">Batal</button><button class="primary">Simpan Setoran Kas</button></div></div></form>');$('skf').onsubmit=async e=>{e.preventDefault();try{await api('/api/setoran/campaigns/'+current.campaign.id+'/cash',{method:'POST',body:JSON.stringify({user_id:Number($('sku').value),amount:Number($('ska').value),note:$('skn').value})});closeM();await load(current.campaign.id);toast('Setoran Kas berhasil masuk ke Kas')}catch(x){toast(x.message)}}};
  window.setoranHistory=function(){openM('Riwayat Setoran — '+esc(current.campaign.name),'<div class="setHistory">'+(current.transactions.map(t=>'<div class="setHistoryRow"><span>'+new Date(t.created_at).toLocaleString('id-ID')+'</span><span><b>'+esc(t.user)+'</b><br><span class="setMuted">'+esc(t.item_name)+'</span></span><b>'+qty(t.quantity)+'</b><span class="setMuted">'+esc(t.note||'-')+'</span><button class="btn" onclick="setoranEditTransaction('+t.id+')">Koreksi</button></div>').join('')||'<div class="setMuted">Belum ada transaksi.</div>')+'</div><div class="modalactions"><button class="btn" onclick="closeM()">Tutup</button></div>')};
  window.setoranEditTransaction=function(id){let t=current.transactions.find(x=>Number(x.id)===Number(id));if(!t)return;openM('Edit Setoran — '+esc(t.item_name),'<form id="setxedit"><div class="setModalGrid"><div><label>Member</label><input value="'+esc(t.user||'-')+'" disabled></div><div><label>Barang</label><input value="'+esc(t.item_name||'-')+'" disabled></div><div><label>Jumlah Setoran</label><input id="setxq" type="number" min="0.01" step="0.01" required value="'+Number(t.quantity||0)+'"></div><div><label>Catatan</label><input id="setxn" value="'+esc(t.note||'')+'" placeholder="Opsional"></div><div class="setFull setMuted"><b>Koreksi stok otomatis:</b> jika jumlah diturunkan, stok Barang ikut berkurang; jika dinaikkan, stok Barang ikut bertambah. Semua koreksi tercatat di Riwayat Stok.</div><div class="modalactions setFull"><button type="button" class="btn" onclick="setoranHistory()">Batal</button><button class="primary">Simpan Perubahan</button></div></div></form>');$('setxedit').onsubmit=async e=>{e.preventDefault();try{await api('/api/setoran/transactions/'+id,{method:'PUT',body:JSON.stringify({quantity:Number($('setxq').value),note:$('setxn').value})});closeM();await load(current.campaign.id);toast('Setoran diperbarui dan stok Barang disesuaikan')}catch(x){toast(x.message)}}};
  window.setoranExport=()=>{window.location.href='/api/setoran/campaigns/'+current.campaign.id+'/export'};
  function nav(){let n=$('nav');if(n&&!n.querySelector('[data-p="setoran"]')&&allow('setoran')){let b=document.createElement('button');b.dataset.p='setoran';b.textContent='▤ Setoran';b.onclick=()=>show('setoran');n.appendChild(b)}}
  setTimeout(()=>{css();if(window.me)nav()},100);
})();