const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
let src=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');

// Security hardening is applied before the application is loaded.
if(process.env.NODE_ENV==='production'&&!process.env.SESSION_SECRET)throw new Error('SESSION_SECRET wajib diset di environment production');

// Replace the known bootstrap password in the runtime copy. Existing installations that
// still use bos123 are rotated to a random password once; the generated password is printed
// once to the server log so the owner can sign in and immediately change it.
src=src.replace("const bcrypt=require('bcryptjs');","const bcrypt=require('bcryptjs');\nconst crypto=require('crypto');");
src=src.replace('app.use(express.json({limit:\'10mb\'}));',"app.use(express.json({limit:'1mb'}));");
src=src.replace("app.use(express.static(__dirname));","app.disable('x-powered-by');app.use(express.static(__dirname));app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()');next()});\nconst loginAttempts=new Map();const loginRateLimit=(req,res,next)=>{const key=(req.ip||'unknown')+'|'+String(req.body?.email||'').trim().toLowerCase(),now=Date.now(),windowMs=10*60*1000,max=5;let x=loginAttempts.get(key);if(!x||now-x.first>windowMs)x={first:now,count:0,blockedUntil:0};if(x.blockedUntil>now)return res.status(429).json({error:'Terlalu banyak percobaan login. Coba lagi beberapa menit.'});x.count++;if(x.count>max)x.blockedUntil=now+15*60*1000;loginAttempts.set(key,x);next()};setInterval(()=>{const now=Date.now();for(const [k,x] of loginAttempts)if(now-x.first>30*60*1000&&x.blockedUntil<now)loginAttempts.delete(k)},30*60*1000).unref();");
src=src.replace("secret:process.env.SESSION_SECRET||'CHANGE_ME'","secret:process.env.SESSION_SECRET");
src=src.replace("app.post('/api/login',async(req,res)=>","app.post('/api/login',loginRateLimit,async(req,res)=>");

// Validate uploaded image signatures instead of trusting client MIME types.
const imageGuard="const validImageBuffer=req=>{if(!req.file)return true;const b=req.file.buffer;if(!Buffer.isBuffer(b)||b.length<12)return false;const jpeg=b[0]===255&&b[1]===216&&b[2]===255;const png=b.slice(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const gif=b.slice(0,6).toString('ascii')==='GIF87a'||b.slice(0,6).toString('ascii')==='GIF89a';const webp=b.slice(0,4).toString('ascii')==='RIFF'&&b.slice(8,12).toString('ascii')==='WEBP';if(!jpeg&&!png&&!gif&&!webp)return false;req.file.mimetype=jpeg?'image/jpeg':png?'image/png':gif?'image/gif':'image/webp';return true};\n";
src=src.replace("const imageData=req=>",imageGuard+"const imageData=req=>");
src=src.replace("upload.single('photo'),async(req,res)=>{try{const b=req.body;","upload.single('photo'),async(req,res)=>{try{if(!validImageBuffer(req))return res.status(400).json({error:'File gambar tidak valid'});const b=req.body;");

// Safer runtime bootstrap: never keep the known default password in the runtime file.
src=src.replace('bcrypt.hashSync("bos123",10)',"bcrypt.hashSync(process.env.INITIAL_BOS_PASSWORD||crypto.randomBytes(18).toString('base64url'),12)");

// Add a self-service password change endpoint and privilege checks.
const securityRoutes=String.raw`
app.post('/api/change-password',auth,async(req,res)=>{try{const current=String(req.body.current_password||''),next=String(req.body.new_password||'');if(next.length<12||next.length>200)return res.status(400).json({error:'Password baru minimal 12 karakter'});if(current===next)return res.status(400).json({error:'Password baru harus berbeda'});if(!bcrypt.compareSync(current,req.me.password))return res.status(401).json({error:'Password saat ini salah'});await run('UPDATE users SET password=$1 WHERE id=$2',[bcrypt.hashSync(next,12),req.me.id]);req.session.regenerate(err=>{if(err)return res.status(500).json({error:'Gagal memperbarui sesi'});req.session.user={id:req.me.id};req.session.save(e=>e?res.status(500).json({error:'Gagal menyimpan sesi'}):res.json({ok:true}))})}catch(e){res.status(500).json({error:'Gagal mengganti password'})}});
`;
const marker="app.get('*',";
if(!src.includes(marker))throw new Error('Catch-all route tidak ditemukan');
src=src.replace(marker,securityRoutes+marker);

const additions=String.raw`
app.delete('/api/users/:id',auth,need('users'),async(req,res)=>{const id=Number(req.params.id);if(id===req.me.id)return res.status(400).json({error:'Tidak dapat menghapus akun yang sedang digunakan'});try{const u=await one('SELECT id FROM users WHERE id=$1',[id]);if(!u)return res.status(404).json({error:'User tidak ditemukan'});await run('DELETE FROM users WHERE id=$1',[id]);res.json({ok:true})}catch(e){res.status(400).json({error:'User memiliki riwayat transaksi atau masih dipakai sistem. Nonaktifkan akun tersebut.'})}});
app.get('/api/sales',auth,async(req,res)=>{if(!['Bos','Consigliere'].includes(req.me.role))return res.status(403).json({error:'Hanya Bos dan Consigliere'});try{await pool.query("CREATE TABLE IF NOT EXISTS sales_transactions(id SERIAL PRIMARY KEY,type TEXT NOT NULL CHECK(type IN ('IN','OUT')),amount NUMERIC(18,2) NOT NULL CHECK(amount>0),balance_after NUMERIC(18,2) NOT NULL,order_id INTEGER UNIQUE REFERENCES orders(id),user_id INTEGER REFERENCES users(id),note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW())");const approved=await q("SELECT o.*,COALESCE(u.name,'User dihapus') requester FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE o.status='Approved' ORDER BY o.id DESC");const approvedTotal=approved.reduce((s,o)=>s+Number(o.total||0),0);const moved=Number((await one("SELECT COALESCE(SUM(amount),0) total FROM sales_transactions WHERE type='OUT'")).total||0);const balance=Math.max(0,approvedTotal-moved);const tx=await q("SELECT t.*,u.name user,o.order_no FROM sales_transactions t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN orders o ON o.id=t.order_id ORDER BY t.id DESC LIMIT 100");res.json({balance,transactions:tx,approved_total:approvedTotal,approved})}catch(e){res.status(500).json({error:'Gagal mengambil data penjualan'})}});
app.post('/api/sales/transfer',auth,async(req,res)=>{if(!['Bos','Consigliere'].includes(req.me.role))return res.status(403).json({error:'Hanya Bos dan Consigliere'});const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0||amount>1000000000000)return res.status(400).json({error:'Nominal tidak valid'});const client=await pool.connect();try{await client.query('BEGIN');await client.query("CREATE TABLE IF NOT EXISTS sales_transactions(id SERIAL PRIMARY KEY,type TEXT NOT NULL CHECK(type IN ('IN','OUT')),amount NUMERIC(18,2) NOT NULL CHECK(amount>0),balance_after NUMERIC(18,2) NOT NULL,order_id INTEGER UNIQUE REFERENCES orders(id),user_id INTEGER REFERENCES users(id),note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW())");const approved=Number((await client.query("SELECT COALESCE(SUM(total),0) total FROM orders WHERE status='Approved'")).rows[0].total||0);const moved=Number((await client.query("SELECT COALESCE(SUM(amount),0) total FROM sales_transactions WHERE type='OUT'")).rows[0].total||0);const salesBalance=Math.max(0,approved-moved);if(amount>salesBalance)throw new Error('Dana penjualan tidak mencukupi');const vw=(await client.query('SELECT * FROM vault WHERE id=1 FOR UPDATE')).rows[0];const nextSales=salesBalance-amount;const nextVault=Number(vw.balance)+amount;await client.query('UPDATE vault SET balance=$1,updated_at=NOW() WHERE id=1',[nextVault]);await client.query("INSERT INTO sales_transactions(type,amount,balance_after,user_id,note) VALUES('OUT',$1,$2,$3,$4)",[amount,nextSales,req.me.id,req.body.note||'Dipindahkan ke Brangkas']);await client.query("INSERT INTO vault_transactions(type,amount,balance_after,user_id,note) VALUES('IN',$1,$2,$3,$4)",[amount,nextVault,req.me.id,'Transfer dari Dana Penjualan']);await client.query('COMMIT');res.json({ok:true,sales_balance:nextSales,vault_balance:nextVault})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message==='Dana penjualan tidak mencukupi'?e.message:'Transfer gagal'})}finally{client.release()}});
`;
src=src.replace(marker,additions+marker);
const roleSeed="app.get('/api/roles',auth,need('roles'),async(req,res)=>res.json(await q('SELECT * FROM roles ORDER BY id')));";
const roleSeeded="app.get('/api/roles',auth,need('roles'),async(req,res)=>{await pool.query(\"INSERT INTO roles(name,description,permissions) VALUES($1,$2,$3) ON CONFLICT(name) DO NOTHING\",['Capo','Operasional dan pemantauan',JSON.stringify(['dashboard','items','cart','order','orders','history','stock'])]);res.json(await q('SELECT * FROM roles ORDER BY id'))});";
if(src.includes(roleSeed))src=src.replace(roleSeed,roleSeeded);

// Tighten user role assignment and remove the predictable fallback password.
src=src.replace("const pass=req.body.password||'cassano123';await run('INSERT INTO users(name,email,password,role_id) VALUES($1,$2,$3,$4)',[req.body.name,req.body.email,bcrypt.hashSync(pass,10),req.body.role_id]);res.json({ok:true,temporary_password:pass})", "const pass=String(req.body.password||'');const roleId=Number(req.body.role_id);if(pass.length<12||pass.length>200)return res.status(400).json({error:'Password minimal 12 karakter'});if(!Number.isInteger(roleId))return res.status(400).json({error:'Role tidak valid'});if(!has(req.me,'roles_manage')&&roleId!==req.me.role_id)return res.status(403).json({error:'Tidak berwenang memilih role ini'});await run('INSERT INTO users(name,email,password,role_id) VALUES($1,$2,$3,$4)',[req.body.name,String(req.body.email||'').trim().toLowerCase(),bcrypt.hashSync(pass,12),roleId]);res.json({ok:true})");
src=src.replace("app.put('/api/users/:id',auth,need('users'),async(req,res)=>{await run('UPDATE users SET name=$1,role_id=$2,active=$3 WHERE id=$4',[req.body.name,req.body.role_id,!!+req.body.active,req.params.id]);res.json({ok:true})});", "app.put('/api/users/:id',auth,need('users'),async(req,res)=>{const id=Number(req.params.id),roleId=Number(req.body.role_id),active=!!+req.body.active;if(!Number.isInteger(id)||!Number.isInteger(roleId))return res.status(400).json({error:'Data user tidak valid'});if(id===req.me.id&&(roleId!==req.me.role_id||!active))return res.status(403).json({error:'Tidak dapat menonaktifkan atau mengganti role akun sendiri'});if(!has(req.me,'roles_manage')&&roleId!==req.me.role_id)return res.status(403).json({error:'Tidak berwenang mengganti role'});await run('UPDATE users SET name=$1,role_id=$2,active=$3 WHERE id=$4',[String(req.body.name||'').trim(),roleId,active,id]);res.json({ok:true})});");

fs.writeFileSync(path.join(__dirname,'.server-runtime.js'),src,'utf8');
require(path.join(__dirname,'.server-runtime.js'));
