const fs=require('fs');
const path=require('path');
const src=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');
const additions=String.raw`
app.delete('/api/users/:id',auth,need('users'),async(req,res)=>{const id=Number(req.params.id);if(id===req.me.id)return res.status(400).json({error:'Tidak dapat menghapus akun yang sedang digunakan'});try{const u=await one('SELECT id FROM users WHERE id=$1',[id]);if(!u)return res.status(404).json({error:'User tidak ditemukan'});await run('DELETE FROM users WHERE id=$1',[id]);res.json({ok:true})}catch(e){res.status(400).json({error:'User memiliki riwayat transaksi atau masih dipakai sistem. Nonaktifkan akun tersebut.'})}});
app.get('/api/sales',auth,async(req,res)=>{if(!['Bos','Consigliere'].includes(req.me.role))return res.status(403).json({error:'Hanya Bos dan Consigliere'});try{await pool.query("CREATE TABLE IF NOT EXISTS sales_transactions(id SERIAL PRIMARY KEY,type TEXT NOT NULL CHECK(type IN ('IN','OUT')),amount NUMERIC(18,2) NOT NULL CHECK(amount>0),balance_after NUMERIC(18,2) NOT NULL,order_id INTEGER UNIQUE REFERENCES orders(id),user_id INTEGER REFERENCES users(id),note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW())");const approved=Number((await one("SELECT COALESCE(SUM(total),0) total FROM orders WHERE status='Approved'")).total||0);const moved=Number((await one("SELECT COALESCE(SUM(amount),0) total FROM sales_transactions WHERE type='OUT'")).total||0);const balance=Math.max(0,approved-moved);const tx=await q("SELECT t.*,u.name user,o.order_no FROM sales_transactions t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN orders o ON o.id=t.order_id ORDER BY t.id DESC LIMIT 100");res.json({balance,transactions:tx,approved_total:approved})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/sales/transfer',auth,async(req,res)=>{if(!['Bos','Consigliere'].includes(req.me.role))return res.status(403).json({error:'Hanya Bos dan Consigliere'});const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Nominal tidak valid'});const client=await pool.connect();try{await client.query('BEGIN');await client.query("CREATE TABLE IF NOT EXISTS sales_transactions(id SERIAL PRIMARY KEY,type TEXT NOT NULL CHECK(type IN ('IN','OUT')),amount NUMERIC(18,2) NOT NULL CHECK(amount>0),balance_after NUMERIC(18,2) NOT NULL,order_id INTEGER UNIQUE REFERENCES orders(id),user_id INTEGER REFERENCES users(id),note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW())");const approved=Number((await client.query("SELECT COALESCE(SUM(total),0) total FROM orders WHERE status='Approved'")).rows[0].total||0);const moved=Number((await client.query("SELECT COALESCE(SUM(amount),0) total FROM sales_transactions WHERE type='OUT'")).rows[0].total||0);const salesBalance=Math.max(0,approved-moved);if(amount>salesBalance)throw new Error('Dana penjualan tidak mencukupi');const vw=(await client.query('SELECT * FROM vault WHERE id=1 FOR UPDATE')).rows[0];const nextSales=salesBalance-amount;const nextVault=Number(vw.balance)+amount;await client.query('UPDATE vault SET balance=$1,updated_at=NOW() WHERE id=1',[nextVault]);await client.query("INSERT INTO sales_transactions(type,amount,balance_after,user_id,note) VALUES('OUT',$1,$2,$3,$4)",[amount,nextSales,req.me.id,req.body.note||'Dipindahkan ke Brangkas']);await client.query("INSERT INTO vault_transactions(type,amount,balance_after,user_id,note) VALUES('IN',$1,$2,$3,$4)",[amount,nextVault,req.me.id,'Transfer dari Dana Penjualan']);await client.query('COMMIT');res.json({ok:true,sales_balance:nextSales,vault_balance:nextVault})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
`;
let patched=src;
const marker="app.get('*',";
if(!patched.includes(marker))throw new Error('Catch-all route tidak ditemukan');
patched=patched.replace(marker,additions+marker);
const roleSeed="app.get('/api/roles',auth,need('roles'),async(req,res)=>res.json(await q('SELECT * FROM roles ORDER BY id')));";
const roleSeeded="app.get('/api/roles',auth,need('roles'),async(req,res)=>{await pool.query(\"INSERT INTO roles(name,description,permissions) VALUES($1,$2,$3) ON CONFLICT(name) DO NOTHING\",['Capo','Operasional dan pemantauan',JSON.stringify(['dashboard','items','cart','order','orders','history','stock'])]);res.json(await q('SELECT * FROM roles ORDER BY id'))});";
if(patched.includes(roleSeed))patched=patched.replace(roleSeed,roleSeeded);
fs.writeFileSync(path.join(__dirname,'.server-runtime.js'),patched,'utf8');
require(path.join(__dirname,'.server-runtime.js'));
